import type {
  Program,
  Testimonial,
  CareerPath,
  SuccessStory,
} from "./types";

export const seedPrograms: Program[] = [
  {
    slug: "ai-ml",
    title: "AI & Machine Learning",
    category: "AI/ML",
    level: "Beginner to Advanced",
    duration: "24 Weeks",
    price_inr: 34999,
    rating: 4.9,
    short_desc: "Build, train, and deploy intelligent systems from neural nets to LLMs.",
    description:
      "An immersive program that takes you from Python foundations to production-grade AI. Work on real datasets, build deep learning models, and ship an end-to-end AI product with mentor guidance.",
    syllabus: [
      "Python & Math for AI",
      "Machine Learning Foundations",
      "Deep Learning & Neural Networks",
      "Computer Vision",
      "Natural Language Processing & LLMs",
      "MLOps & Model Deployment",
    ],
    tags: ["Python", "TensorFlow", "PyTorch", "LLMs"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Image Classifier", desc: "CNN that recognizes objects in real photos." },
      { title: "Sentiment Engine", desc: "NLP model scoring reviews at scale." },
      { title: "Recommendation System", desc: "Personalized suggestions from user data." },
      { title: "Chatbot with LLMs", desc: "Retrieval-augmented assistant." },
      { title: "Face Detection App", desc: "Real-time computer vision pipeline." },
      { title: "Capstone AI Product", desc: "End-to-end deployed AI service." },
    ],
    mentors: [
      { name: "Dr. Kavya Rao", role: "AI Lead, ex-Google", bio: "10+ years building ML systems at scale." },
      { name: "Arjun Mehta", role: "Senior ML Engineer", bio: "Specialist in NLP and LLM deployment." },
    ],
    tools: ["Python", "TensorFlow", "PyTorch", "Hugging Face", "Docker"],
    outcomes: ["Job-ready AI portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "data-science-ml",
    title: "Data Science & Machine Learning",
    category: "Data Science",
    level: "Intermediate",
    duration: "20 Weeks",
    price_inr: 29999,
    rating: 4.9,
    short_desc: "From Python and statistics to deep learning and model deployment.",
    description:
      "Become a job-ready data scientist. Learn data wrangling, visualization, machine learning algorithms, and how to deploy models to production with real-world datasets.",
    syllabus: [
      "Python for Data Science",
      "Statistics & Probability",
      "Pandas, NumPy & Visualization",
      "Machine Learning with scikit-learn",
      "Deep Learning with TensorFlow",
      "Model Deployment & MLOps",
    ],
    tags: ["Python", "MachineLearning", "TensorFlow", "Pandas"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Sales Forecasting", desc: "Time-series model predicting revenue." },
      { title: "Customer Segmentation", desc: "Clustering users for targeting." },
      { title: "Churn Prediction", desc: "Classify at-risk customers." },
      { title: "A/B Test Analysis", desc: "Statistical experiment evaluation." },
      { title: "Interactive Dashboard", desc: "Business KPIs visualized." },
      { title: "Capstone Analysis", desc: "End-to-end data product." },
    ],
    mentors: [
      { name: "Neha Gupta", role: "Lead Data Scientist", bio: "Drives analytics for a top fintech." },
      { name: "Vikram Singh", role: "Data Science Mentor", bio: "Ex-Amazon, ML & analytics expert." },
    ],
    tools: ["Python", "Pandas", "SQL", "Tableau", "scikit-learn"],
    outcomes: ["Analytics portfolio", "6 real projects", "Placement assistance"],
  },
  {
    slug: "cybersecurity-essentials",
    title: "Cybersecurity Essentials",
    category: "Cybersecurity",
    level: "Beginner to Intermediate",
    duration: "14 Weeks",
    price_inr: 26999,
    rating: 4.7,
    short_desc: "Protect systems and networks with hands-on ethical hacking labs.",
    description:
      "Understand security fundamentals, threat models, and defensive techniques. Practice penetration testing, network security, and incident response in guided labs.",
    syllabus: [
      "Security Fundamentals",
      "Network Security",
      "Ethical Hacking & Pen Testing",
      "Web Application Security",
      "Cryptography Basics",
      "Incident Response",
    ],
    tags: ["Security", "EthicalHacking", "Networking"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Vulnerability Scan", desc: "Assess and report system weaknesses." },
      { title: "Web Pen Test", desc: "Exploit and secure a sample app." },
      { title: "Network Defense Lab", desc: "Configure firewalls and IDS." },
      { title: "Phishing Simulation", desc: "Run and analyze an awareness campaign." },
      { title: "Incident Response Drill", desc: "Detect, contain, and recover." },
      { title: "Capstone Security Audit", desc: "Full assessment of a target system." },
    ],
    mentors: [
      { name: "Rahul Khanna", role: "Security Architect", bio: "CISSP, 12 years in offensive security." },
      { name: "Ananya Iyer", role: "SOC Lead", bio: "Incident response and threat hunting." },
    ],
    tools: ["Kali", "Wireshark", "Metasploit", "Burp", "Nmap"],
    outcomes: ["Hands-on hacking labs", "6 security projects", "Placement assistance"],
  },
  {
    slug: "hr-management",
    title: "HR Management & Analytics",
    category: "HR",
    level: "Beginner to Intermediate",
    duration: "12 Weeks",
    price_inr: 17999,
    rating: 4.7,
    short_desc: "Modern people operations: hiring, engagement, and HR analytics.",
    description:
      "A practical program blending core HR practice with data-driven decision making. Learn recruitment, employee engagement, labor compliance, and how to use analytics to build better teams.",
    syllabus: [
      "Foundations of HR",
      "Talent Acquisition & Recruitment",
      "Employee Engagement & Culture",
      "Compensation & Benefits",
      "HR Analytics & Dashboards",
      "Labor Law & Compliance",
    ],
    tags: ["HR", "Recruitment", "People Analytics"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Recruitment Funnel", desc: "Design and measure a hiring pipeline." },
      { title: "Engagement Survey", desc: "Build and analyze employee feedback." },
      { title: "Compensation Plan", desc: "Structure fair, competitive pay bands." },
      { title: "Attrition Dashboard", desc: "Visualize and predict turnover." },
      { title: "Onboarding Program", desc: "Design a 90-day onboarding journey." },
      { title: "Capstone HR Strategy", desc: "Full people strategy for a company." },
    ],
    mentors: [
      { name: "Meera Joshi", role: "Head of People", bio: "Scaled HR for high-growth startups." },
      { name: "Sanjay Patel", role: "HR Analytics Lead", bio: "Turns people data into strategy." },
    ],
    tools: ["Excel", "Power BI", "HRIS", "LinkedIn Recruiter"],
    outcomes: ["HR portfolio", "6 practical projects", "Placement assistance"],
  },
  {
    slug: "full-stack-web-development",
    title: "Full-Stack Web Development",
    category: "Web Development",
    level: "Beginner to Advanced",
    duration: "16 Weeks",
    price_inr: 24999,
    rating: 4.8,
    short_desc: "Master React, Node.js, and databases to build production-grade web apps.",
    description:
      "A comprehensive, project-driven bootcamp covering front-end and back-end engineering. Build and deploy real applications while learning industry best practices, version control, and cloud deployment.",
    syllabus: [
      "HTML, CSS & Modern JavaScript",
      "React & Next.js",
      "Node.js, Express & REST APIs",
      "PostgreSQL & Prisma",
      "Authentication & Security",
      "Deployment & CI/CD",
    ],
    tags: ["React", "Node.js", "PostgreSQL", "Next.js"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Portfolio Site", desc: "A responsive personal site built with semantic HTML/CSS." },
      { title: "Task Manager App", desc: "Full CRUD app with React state and hooks." },
      { title: "REST API Service", desc: "Node.js/Express API with authentication." },
      { title: "E-commerce Storefront", desc: "Next.js storefront with cart and checkout flow." },
      { title: "Realtime Chat App", desc: "WebSocket-powered live messaging app." },
      { title: "Capstone Full-Stack Product", desc: "End-to-end deployed application with CI/CD." },
    ],
    mentors: [
      { name: "Aditya Rao", role: "Full-Stack Engineer", bio: "Ships production React/Node apps at scale." },
      { name: "Kritika Shah", role: "Senior Frontend Engineer", bio: "Specialist in performant, accessible UIs." },
    ],
    tools: ["React", "Next.js", "Node.js", "PostgreSQL", "Git"],
    outcomes: ["Full-stack portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "cloud-devops",
    title: "Cloud Computing & DevOps",
    category: "Cloud & Infrastructure",
    level: "Intermediate",
    duration: "12 Weeks",
    price_inr: 22999,
    rating: 4.7,
    short_desc: "Deploy, automate, and scale applications on AWS with modern DevOps tools.",
    description:
      "Learn to design resilient cloud infrastructure and automate delivery pipelines. Hands-on with AWS, Docker, Kubernetes, Terraform, and CI/CD workflows.",
    syllabus: [
      "Linux & Networking Fundamentals",
      "AWS Core Services",
      "Docker & Containers",
      "Kubernetes Orchestration",
      "Infrastructure as Code with Terraform",
      "CI/CD Pipelines",
    ],
    tags: ["AWS", "Docker", "Kubernetes", "Terraform"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "CI/CD Pipeline", desc: "Automated build-test-deploy pipeline." },
      { title: "Containerized Microservice", desc: "Dockerized service deployed to the cloud." },
      { title: "Kubernetes Cluster Deployment", desc: "Orchestrate a multi-service app on K8s." },
      { title: "Infrastructure as Code", desc: "Provision cloud resources with Terraform." },
      { title: "Monitoring & Alerting Setup", desc: "Observability stack for a live service." },
      { title: "Capstone Cloud Architecture", desc: "End-to-end resilient infrastructure design." },
    ],
    mentors: [
      { name: "Farhan Ali", role: "Cloud Architect", bio: "Designs resilient AWS infrastructure for scale-ups." },
      { name: "Divya Menon", role: "DevOps Lead", bio: "Automates delivery pipelines for fast-moving teams." },
    ],
    tools: ["AWS", "Docker", "Kubernetes", "Terraform", "GitHub Actions"],
    outcomes: ["Cloud & DevOps portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design Masterclass",
    category: "Design",
    level: "Beginner",
    duration: "10 Weeks",
    price_inr: 18999,
    rating: 4.8,
    short_desc: "Design beautiful, user-centered products with Figma and design systems.",
    description:
      "Learn the full product design process: research, wireframing, prototyping, and building scalable design systems. Create a portfolio of real case studies.",
    syllabus: [
      "Design Thinking & Research",
      "Wireframing & Prototyping",
      "Figma Deep Dive",
      "Design Systems",
      "Usability Testing",
      "Portfolio Building",
    ],
    tags: ["Figma", "UX", "UI", "DesignSystems"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "UX Research Case Study", desc: "User interviews and journey mapping for a real product." },
      { title: "Wireframe to Prototype", desc: "Low to high-fidelity interactive prototype." },
      { title: "Design System Build", desc: "Reusable component library in Figma." },
      { title: "Mobile App Redesign", desc: "End-to-end redesign of an existing app flow." },
      { title: "Usability Testing Report", desc: "Run tests and synthesize actionable findings." },
      { title: "Capstone Product Case Study", desc: "Full case study ready for a design portfolio." },
    ],
    mentors: [
      { name: "Ishita Kapoor", role: "Lead Product Designer", bio: "Has shipped design systems for consumer apps." },
      { name: "Rohit Nair", role: "UX Researcher", bio: "Turns user research into product decisions." },
    ],
    tools: ["Figma", "Figjam", "Adobe XD", "Maze"],
    outcomes: ["Design portfolio", "6 real case studies", "Placement assistance"],
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development with React Native",
    category: "Mobile",
    level: "Intermediate",
    duration: "12 Weeks",
    price_inr: 21999,
    rating: 4.6,
    short_desc: "Build cross-platform iOS and Android apps from a single codebase.",
    description:
      "Create native-quality mobile apps using React Native and Expo. Cover navigation, state management, native APIs, and publishing to app stores.",
    syllabus: [
      "React Native Fundamentals",
      "Expo & Tooling",
      "Navigation & State",
      "Native Device APIs",
      "Push Notifications",
      "App Store Deployment",
    ],
    tags: ["ReactNative", "Expo", "Mobile"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "To-Do List App", desc: "Cross-platform app with local storage." },
      { title: "Weather App", desc: "Consumes a live API with location services." },
      { title: "Social Feed App", desc: "Infinite scroll feed with native gestures." },
      { title: "E-commerce App", desc: "Cart, checkout, and push notifications." },
      { title: "Chat Application", desc: "Realtime messaging with native performance." },
      { title: "Capstone Published App", desc: "App submitted to the App Store / Play Store." },
    ],
    mentors: [
      { name: "Naveen Kumar", role: "Mobile Engineering Lead", bio: "Has shipped React Native apps used by millions." },
      { name: "Pooja Iyer", role: "Mobile Developer", bio: "Specialist in native performance and animations." },
    ],
    tools: ["React Native", "Expo", "Firebase", "TypeScript"],
    outcomes: ["Published app", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "data-analytics",
    title: "Data Analytics",
    category: "Data Science",
    level: "Beginner to Intermediate",
    duration: "16 Weeks",
    price_inr: 24999,
    rating: 4.8,
    short_desc: "Turn raw data into decisions with SQL, Excel, Python, and BI dashboards.",
    description:
      "A hands-on analytics program covering the full workflow — cleaning, querying, analysing, and visualising data. Build interactive dashboards and tell stories that drive business decisions.",
    syllabus: [
      "Excel & Spreadsheet Analytics",
      "SQL for Analysts",
      "Python (Pandas & NumPy)",
      "Statistics for Analytics",
      "Data Visualization & Storytelling",
      "Power BI & Tableau Dashboards",
    ],
    tags: ["SQL", "Python", "Power BI", "Tableau"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Sales Dashboard", desc: "Interactive KPI dashboard in Power BI." },
      { title: "SQL Case Study", desc: "Answer business questions from a real database." },
      { title: "Customer Cohort Analysis", desc: "Retention and cohort insights in Python." },
      { title: "Marketing Funnel Report", desc: "Analyse conversion across channels." },
      { title: "Financial Trends Report", desc: "Visualise revenue and cost trends." },
      { title: "Capstone Analytics Project", desc: "End-to-end data story for a client brief." },
    ],
    mentors: [
      { name: "Sneha Prabhu", role: "Lead Data Analyst", bio: "8+ years turning data into business strategy." },
      { name: "Rahul Nair", role: "BI Developer", bio: "Builds enterprise dashboards used by leadership teams." },
    ],
    tools: ["SQL", "Excel", "Python", "Power BI", "Tableau"],
    outcomes: ["Analytics portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "machine-learning",
    title: "Machine Learning",
    category: "AI/ML",
    level: "Intermediate",
    duration: "18 Weeks",
    price_inr: 29999,
    rating: 4.8,
    short_desc: "Master supervised, unsupervised, and deep learning to build predictive models.",
    description:
      "A focused machine learning program that takes you from core algorithms to production models. Work through regression, classification, ensembles, and neural networks on real datasets.",
    syllabus: [
      "Python & ML Math",
      "Supervised Learning",
      "Unsupervised Learning",
      "Ensemble Methods",
      "Neural Networks",
      "Model Deployment & MLOps",
    ],
    tags: ["Python", "scikit-learn", "TensorFlow", "ML"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "House Price Predictor", desc: "Regression model on real estate data." },
      { title: "Spam Classifier", desc: "Text classification pipeline." },
      { title: "Customer Clustering", desc: "Unsupervised segmentation project." },
      { title: "Credit Risk Model", desc: "Ensemble model for default prediction." },
      { title: "Digit Recognizer", desc: "Neural network on image data." },
      { title: "Capstone ML Service", desc: "Deployed model with a REST API." },
    ],
    mentors: [
      { name: "Dr. Anil Verma", role: "ML Scientist", bio: "Researcher with production ML at scale." },
      { name: "Divya Menon", role: "ML Engineer", bio: "Specialist in model deployment and MLOps." },
    ],
    tools: ["Python", "scikit-learn", "TensorFlow", "Pandas", "Docker"],
    outcomes: ["ML project portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "hybrid-electric-vehicle",
    title: "Hybrid Electric Vehicle",
    category: "Electronics & Hardware",
    level: "Intermediate",
    duration: "12 Weeks",
    price_inr: 27999,
    rating: 4.7,
    short_desc: "Understand EV/HEV powertrains, battery systems, and motor control.",
    description:
      "A specialised program on hybrid and electric vehicle technology. Cover powertrain architectures, battery management, motor drives, and control strategies used in modern EVs.",
    syllabus: [
      "EV & HEV Fundamentals",
      "Battery Technology & BMS",
      "Electric Motors & Drives",
      "Power Electronics",
      "Vehicle Control Systems",
      "Charging Infrastructure",
    ],
    tags: ["EV", "Battery", "Powertrain", "Automotive"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Battery Pack Sizing", desc: "Design a pack for a target range." },
      { title: "BMS Simulation", desc: "Model cell balancing and protection." },
      { title: "Motor Control Model", desc: "Simulate a traction motor drive." },
      { title: "Regen Braking Study", desc: "Analyse energy recovery efficiency." },
      { title: "Charging Profile Analysis", desc: "Evaluate fast-charging strategies." },
      { title: "Capstone EV Powertrain", desc: "End-to-end powertrain design report." },
    ],
    mentors: [
      { name: "Karthik Reddy", role: "EV Systems Engineer", bio: "Designs powertrains for electric mobility startups." },
      { name: "Meera Joshi", role: "Battery Engineer", bio: "Specialist in BMS and pack design." },
    ],
    tools: ["MATLAB", "Simulink", "PSpice", "Python"],
    outcomes: ["EV engineering portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "business-analyst",
    title: "Business Analyst",
    category: "Business & Management",
    level: "Beginner to Intermediate",
    duration: "14 Weeks",
    price_inr: 24999,
    rating: 4.7,
    short_desc: "Bridge business and tech with requirements, analysis, and stakeholder skills.",
    description:
      "Become a job-ready business analyst. Learn requirement gathering, process modelling, data-driven decision-making, and the documentation that keeps projects on track.",
    syllabus: [
      "Business Analysis Foundations",
      "Requirement Elicitation",
      "Process Modelling (BPMN)",
      "SQL & Data Analysis",
      "Agile & User Stories",
      "Stakeholder Management",
    ],
    tags: ["BA", "SQL", "Agile", "BPMN"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Requirements Document", desc: "BRD/FRD for a sample product." },
      { title: "Process Map", desc: "As-is and to-be BPMN diagrams." },
      { title: "SQL Insights Report", desc: "Answer stakeholder questions from data." },
      { title: "User Story Backlog", desc: "Groomed backlog with acceptance criteria." },
      { title: "Gap Analysis", desc: "Identify and prioritise improvements." },
      { title: "Capstone BA Case Study", desc: "Full analysis for a business scenario." },
    ],
    mentors: [
      { name: "Aditya Rao", role: "Senior Business Analyst", bio: "10+ years across fintech and SaaS." },
      { name: "Nisha Gupta", role: "Product Analyst", bio: "Turns stakeholder needs into shippable specs." },
    ],
    tools: ["SQL", "Jira", "Excel", "Power BI", "Miro"],
    outcomes: ["BA portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "iot-robotics",
    title: "IoT & Robotics",
    category: "Electronics & Hardware",
    level: "Beginner to Intermediate",
    duration: "16 Weeks",
    price_inr: 26999,
    rating: 4.7,
    short_desc: "Build connected devices and robots with sensors, microcontrollers, and the cloud.",
    description:
      "A practical program blending IoT and robotics. Program microcontrollers, wire up sensors and actuators, connect devices to the cloud, and build robots that sense and act.",
    syllabus: [
      "Electronics & Microcontrollers",
      "Sensors & Actuators",
      "Arduino & Raspberry Pi",
      "IoT Protocols (MQTT)",
      "Cloud Integration",
      "Robotics & Automation",
    ],
    tags: ["Arduino", "RaspberryPi", "MQTT", "Robotics"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Smart Home Sensor", desc: "Temperature and motion monitoring node." },
      { title: "IoT Dashboard", desc: "Live device data streamed to the cloud." },
      { title: "Line-Following Robot", desc: "Sensor-driven autonomous robot." },
      { title: "Weather Station", desc: "Multi-sensor node with data logging." },
      { title: "Voice-Controlled Device", desc: "IoT device with voice commands." },
      { title: "Capstone Robotics Project", desc: "End-to-end connected robotic system." },
    ],
    mentors: [
      { name: "Vikram Shetty", role: "IoT Architect", bio: "Builds connected products for smart industry." },
      { name: "Anjali Desai", role: "Robotics Engineer", bio: "Specialist in embedded control and automation." },
    ],
    tools: ["Arduino", "Raspberry Pi", "MQTT", "Node-RED", "Python"],
    outcomes: ["Hardware portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "vlsi",
    title: "VLSI",
    category: "Electronics & Hardware",
    level: "Intermediate to Advanced",
    duration: "20 Weeks",
    price_inr: 32999,
    rating: 4.8,
    short_desc: "Design digital chips from RTL to layout with industry-standard flows.",
    description:
      "A rigorous VLSI program covering the full chip-design flow. Learn Verilog, digital design, synthesis, and physical design used by leading semiconductor companies.",
    syllabus: [
      "Digital Electronics",
      "Verilog HDL",
      "RTL Design",
      "Synthesis & STA",
      "Physical Design",
      "Design Verification",
    ],
    tags: ["Verilog", "RTL", "ASIC", "FPGA"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "ALU Design", desc: "RTL design and simulation of an ALU." },
      { title: "FIFO Controller", desc: "Synchronous FIFO in Verilog." },
      { title: "UART Module", desc: "Design and verify a UART block." },
      { title: "FPGA Prototype", desc: "Deploy a design to an FPGA board." },
      { title: "Timing Closure Study", desc: "Static timing analysis of a block." },
      { title: "Capstone Chip Block", desc: "RTL-to-GDSII flow for a sub-system." },
    ],
    mentors: [
      { name: "Suresh Iyer", role: "VLSI Design Engineer", bio: "Taped out chips at leading semiconductor firms." },
      { name: "Lakshmi Rao", role: "Verification Engineer", bio: "Specialist in RTL verification methodologies." },
    ],
    tools: ["Verilog", "Cadence", "Synopsys", "Xilinx Vivado"],
    outcomes: ["VLSI project portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "embedded-systems",
    title: "Embedded Systems",
    category: "Electronics & Hardware",
    level: "Intermediate",
    duration: "16 Weeks",
    price_inr: 28999,
    rating: 4.7,
    short_desc: "Program microcontrollers and RTOS for real-time embedded products.",
    description:
      "Build firmware for real-world embedded devices. Master embedded C, microcontroller peripherals, communication protocols, and real-time operating systems.",
    syllabus: [
      "Embedded C Programming",
      "Microcontroller Architecture",
      "Peripherals & Interrupts",
      "Communication Protocols (I2C/SPI/UART)",
      "RTOS Fundamentals",
      "Firmware Debugging",
    ],
    tags: ["Embedded C", "ARM", "RTOS", "Firmware"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "LED Controller", desc: "PWM-based lighting control." },
      { title: "Sensor Data Logger", desc: "Read and store sensor data over I2C." },
      { title: "Motor Driver", desc: "Control a motor with feedback." },
      { title: "RTOS Scheduler Demo", desc: "Multi-task firmware on an RTOS." },
      { title: "Serial Console", desc: "UART-based command interface." },
      { title: "Capstone Embedded Product", desc: "End-to-end firmware for a device." },
    ],
    mentors: [
      { name: "Ramesh Babu", role: "Embedded Lead", bio: "15+ years shipping firmware for consumer devices." },
      { name: "Fatima Sheikh", role: "Firmware Engineer", bio: "Specialist in RTOS and low-power design." },
    ],
    tools: ["Embedded C", "STM32", "FreeRTOS", "Keil", "Logic Analyzer"],
    outcomes: ["Firmware portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "medical-coding",
    title: "Medical Coding",
    category: "Healthcare",
    level: "Beginner",
    duration: "12 Weeks",
    price_inr: 19999,
    rating: 4.6,
    short_desc: "Learn ICD, CPT, and HCPCS coding for a career in healthcare records.",
    description:
      "A certification-focused program on medical coding. Learn anatomy, medical terminology, and the ICD-10, CPT, and HCPCS code sets used across hospitals and insurers.",
    syllabus: [
      "Medical Terminology",
      "Human Anatomy & Physiology",
      "ICD-10-CM Coding",
      "CPT Coding",
      "HCPCS & Modifiers",
      "Compliance & Billing",
    ],
    tags: ["ICD-10", "CPT", "HCPCS", "Healthcare"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Diagnosis Coding Set", desc: "Assign ICD-10 codes to case notes." },
      { title: "Procedure Coding Set", desc: "Assign CPT codes to procedures." },
      { title: "Claims Scenario", desc: "Code a full patient encounter." },
      { title: "Modifier Practice", desc: "Apply modifiers correctly to claims." },
      { title: "Audit Exercise", desc: "Review charts for coding accuracy." },
      { title: "Capstone Coding Portfolio", desc: "Certification-ready coding samples." },
    ],
    mentors: [
      { name: "Dr. Priya Menon", role: "Certified Coding Trainer", bio: "CPC-certified with hospital coding experience." },
      { name: "Joseph Thomas", role: "Medical Billing Lead", bio: "Specialist in claims and compliance." },
    ],
    tools: ["ICD-10-CM", "CPT", "HCPCS", "EHR Systems"],
    outcomes: ["Certification readiness", "6 practice case sets", "Placement assistance"],
  },
  {
    slug: "autocad",
    title: "Auto CAD",
    category: "Engineering & Design",
    level: "Beginner to Intermediate",
    duration: "8 Weeks",
    price_inr: 15999,
    rating: 4.6,
    short_desc: "Create precise 2D drawings and 3D models for engineering and design.",
    description:
      "A hands-on AutoCAD program for engineers, architects, and designers. Master drafting, dimensioning, and 3D modelling to produce industry-standard technical drawings.",
    syllabus: [
      "AutoCAD Interface & Setup",
      "2D Drafting & Editing",
      "Dimensioning & Annotation",
      "Layers & Blocks",
      "3D Modelling Basics",
      "Plotting & Layouts",
    ],
    tags: ["AutoCAD", "Drafting", "2D", "3D"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Floor Plan", desc: "Complete 2D architectural floor plan." },
      { title: "Mechanical Part", desc: "Dimensioned engineering drawing." },
      { title: "Electrical Layout", desc: "Wiring and circuit layout drawing." },
      { title: "3D Component Model", desc: "3D model of a mechanical part." },
      { title: "Assembly Drawing", desc: "Multi-part assembly with BOM." },
      { title: "Capstone Drawing Set", desc: "Full drawing package for a project." },
    ],
    mentors: [
      { name: "Manoj Pillai", role: "CAD Design Engineer", bio: "12+ years in mechanical drafting." },
      { name: "Sunita Rao", role: "Architectural Drafter", bio: "Specialist in construction documentation." },
    ],
    tools: ["AutoCAD", "AutoCAD 3D", "DWG TrueView"],
    outcomes: ["Drawing portfolio", "6 real-world drawings", "Placement assistance"],
  },
  {
    slug: "construction-planning",
    title: "Construction Planning",
    category: "Engineering & Design",
    level: "Intermediate",
    duration: "12 Weeks",
    price_inr: 22999,
    rating: 4.6,
    short_desc: "Plan, schedule, and cost construction projects with modern PM tools.",
    description:
      "Learn to plan and control construction projects end to end — scheduling, estimation, resource planning, and project controls using industry tools like Primavera and MS Project.",
    syllabus: [
      "Construction Project Lifecycle",
      "Estimation & Costing",
      "Scheduling (CPM)",
      "Primavera P6",
      "Resource & Cost Control",
      "Quality & Safety Management",
    ],
    tags: ["Primavera", "MSProject", "Scheduling", "Estimation"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Project Schedule", desc: "CPM schedule for a building project." },
      { title: "Cost Estimate", desc: "Detailed BOQ and cost estimate." },
      { title: "Resource Plan", desc: "Allocate labour and equipment." },
      { title: "Primavera Model", desc: "Full project plan in Primavera P6." },
      { title: "Progress Report", desc: "Earned value and progress tracking." },
      { title: "Capstone Project Plan", desc: "End-to-end plan for a construction project." },
    ],
    mentors: [
      { name: "Rajesh Kumar", role: "Planning Engineer", bio: "Plans large infrastructure projects." },
      { name: "Deepa Nair", role: "Project Controls Lead", bio: "Specialist in cost and schedule control." },
    ],
    tools: ["Primavera P6", "MS Project", "Excel", "AutoCAD"],
    outcomes: ["Planning portfolio", "6 real-world deliverables", "Placement assistance"],
  },
  {
    slug: "finance",
    title: "Finance",
    category: "Finance",
    level: "Beginner to Intermediate",
    duration: "14 Weeks",
    price_inr: 23999,
    rating: 4.7,
    short_desc: "Master financial analysis, modelling, and valuation for a finance career.",
    description:
      "A career-focused finance program covering accounting foundations, financial modelling, valuation, and corporate finance — with Excel-driven, real-world case work.",
    syllabus: [
      "Accounting Foundations",
      "Financial Statement Analysis",
      "Financial Modelling in Excel",
      "Valuation (DCF & Comparables)",
      "Corporate Finance",
      "Financial Reporting",
    ],
    tags: ["Finance", "Excel", "Valuation", "Modelling"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "3-Statement Model", desc: "Integrated financial model in Excel." },
      { title: "DCF Valuation", desc: "Value a company using DCF." },
      { title: "Ratio Analysis", desc: "Analyse a firm's financial health." },
      { title: "Budget Model", desc: "Build an annual operating budget." },
      { title: "Investment Memo", desc: "Recommendation backed by analysis." },
      { title: "Capstone Finance Case", desc: "Full analysis of a real company." },
    ],
    mentors: [
      { name: "Ashish Malhotra", role: "Finance Manager", bio: "CFA with corporate finance experience." },
      { name: "Ritika Shah", role: "Financial Analyst", bio: "Specialist in modelling and valuation." },
    ],
    tools: ["Excel", "PowerPoint", "Bloomberg", "Tally"],
    outcomes: ["Finance portfolio", "6 real-world case studies", "Placement assistance"],
  },
  {
    slug: "biotechnology",
    title: "Biotechnology",
    category: "Science & Research",
    level: "Beginner to Intermediate",
    duration: "16 Weeks",
    price_inr: 25999,
    rating: 4.6,
    short_desc: "Explore molecular biology, genetics, and lab techniques for biotech careers.",
    description:
      "An applied biotechnology program combining molecular biology theory with lab and analysis skills used across pharma, research, and agri-biotech.",
    syllabus: [
      "Cell & Molecular Biology",
      "Genetics & Genomics",
      "Recombinant DNA Technology",
      "Bioprocess Engineering",
      "Lab Techniques & Safety",
      "Bioethics & Applications",
    ],
    tags: ["Biotech", "Genetics", "Molecular Biology"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "DNA Extraction Study", desc: "Protocol and results write-up." },
      { title: "PCR Analysis", desc: "Design and interpret a PCR experiment." },
      { title: "Gene Cloning Plan", desc: "Design a recombinant DNA workflow." },
      { title: "Fermentation Study", desc: "Bioprocess optimisation report." },
      { title: "Sequence Analysis", desc: "Analyse a gene sequence." },
      { title: "Capstone Biotech Project", desc: "End-to-end applied research report." },
    ],
    mentors: [
      { name: "Dr. Shalini Rao", role: "Biotechnologist", bio: "Research scientist in molecular biology." },
      { name: "Dr. Imran Khan", role: "Bioprocess Specialist", bio: "Industrial fermentation expert." },
    ],
    tools: ["PCR", "Gel Electrophoresis", "BLAST", "Lab Instruments"],
    outcomes: ["Research portfolio", "6 lab/analysis projects", "Placement assistance"],
  },
  {
    slug: "genetic-engineering",
    title: "Genetic Engineering",
    category: "Science & Research",
    level: "Intermediate",
    duration: "16 Weeks",
    price_inr: 27999,
    rating: 4.7,
    short_desc: "Learn gene editing, CRISPR, and recombinant techniques hands-on.",
    description:
      "A specialised program on genetic engineering. Study gene manipulation, CRISPR-Cas systems, cloning strategies, and their applications in medicine and agriculture.",
    syllabus: [
      "Molecular Genetics",
      "Gene Cloning & Vectors",
      "CRISPR-Cas Systems",
      "Gene Expression Analysis",
      "Genome Editing Applications",
      "Bioethics & Regulation",
    ],
    tags: ["CRISPR", "Genetics", "Cloning"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "CRISPR Design", desc: "Design guide RNAs for a target gene." },
      { title: "Vector Construction Plan", desc: "Design a cloning vector strategy." },
      { title: "Knockout Study", desc: "Plan a gene knockout experiment." },
      { title: "Expression Analysis", desc: "Interpret gene expression data." },
      { title: "Editing Case Study", desc: "Application of editing in therapy." },
      { title: "Capstone Engineering Project", desc: "Full genetic engineering proposal." },
    ],
    mentors: [
      { name: "Dr. Neha Kulkarni", role: "Molecular Geneticist", bio: "CRISPR research and gene editing expert." },
      { name: "Dr. Sanjay Rao", role: "Genomics Scientist", bio: "Specialist in genome analysis." },
    ],
    tools: ["CRISPR", "SnapGene", "BLAST", "Lab Instruments"],
    outcomes: ["Research portfolio", "6 applied projects", "Placement assistance"],
  },
  {
    slug: "stock-marketing",
    title: "Stock Marketing",
    category: "Finance",
    level: "Beginner to Intermediate",
    duration: "10 Weeks",
    price_inr: 18999,
    rating: 4.6,
    short_desc: "Learn to analyse and trade stocks with technical and fundamental strategies.",
    description:
      "A practical stock market program covering how markets work, technical and fundamental analysis, risk management, and building a disciplined trading and investing approach.",
    syllabus: [
      "Stock Market Fundamentals",
      "Technical Analysis",
      "Fundamental Analysis",
      "Derivatives & Options",
      "Risk & Portfolio Management",
      "Trading Psychology",
    ],
    tags: ["Trading", "Investing", "TechnicalAnalysis"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Chart Analysis", desc: "Technical analysis of a stock." },
      { title: "Company Valuation", desc: "Fundamental analysis report." },
      { title: "Options Strategy", desc: "Design and back-test a strategy." },
      { title: "Portfolio Build", desc: "Construct a diversified portfolio." },
      { title: "Trade Journal", desc: "Track and review simulated trades." },
      { title: "Capstone Market Case", desc: "Full investment thesis and plan." },
    ],
    mentors: [
      { name: "Vivek Sharma", role: "Market Analyst", bio: "Trader and analyst with a decade of experience." },
      { name: "Kavita Reddy", role: "Portfolio Advisor", bio: "Specialist in risk and portfolio strategy." },
    ],
    tools: ["TradingView", "NSE/BSE Data", "Excel", "Screeners"],
    outcomes: ["Trading playbook", "6 analysis projects", "Placement assistance"],
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    category: "Marketing",
    level: "Beginner to Intermediate",
    duration: "12 Weeks",
    price_inr: 19999,
    rating: 4.7,
    short_desc: "Grow brands online with SEO, ads, social, and analytics.",
    description:
      "A full-funnel digital marketing program. Master SEO, paid ads, social media, content, email, and analytics to run campaigns that drive measurable growth.",
    syllabus: [
      "Digital Marketing Foundations",
      "SEO & Content Marketing",
      "Google & Meta Ads",
      "Social Media Marketing",
      "Email & Automation",
      "Analytics & Conversion",
    ],
    tags: ["SEO", "Ads", "SocialMedia", "Analytics"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "SEO Audit", desc: "Full audit and optimisation plan." },
      { title: "Ad Campaign", desc: "Google/Meta campaign with targeting." },
      { title: "Content Calendar", desc: "Social strategy and calendar." },
      { title: "Email Funnel", desc: "Automated nurture sequence." },
      { title: "Analytics Report", desc: "Measure and report on a campaign." },
      { title: "Capstone Growth Plan", desc: "Full marketing plan for a brand." },
    ],
    mentors: [
      { name: "Rohan Kapoor", role: "Growth Marketer", bio: "Scaled brands with performance marketing." },
      { name: "Sara Ali", role: "SEO Specialist", bio: "Ranks sites and builds content engines." },
    ],
    tools: ["Google Ads", "Meta Ads", "GA4", "SEMrush", "Mailchimp"],
    outcomes: ["Marketing portfolio", "6 real campaigns", "Placement assistance"],
  },
  {
    slug: "psychology-workshop",
    title: "Psychology Workshop",
    category: "Science & Research",
    level: "Beginner",
    duration: "6 Weeks",
    price_inr: 12999,
    rating: 4.6,
    short_desc: "Explore core psychology concepts and their real-world applications.",
    description:
      "An introductory, application-focused psychology workshop. Understand human behaviour, cognition, and emotion, and how psychology applies to work, wellbeing, and relationships.",
    syllabus: [
      "Introduction to Psychology",
      "Cognition & Behaviour",
      "Emotion & Motivation",
      "Personality & Development",
      "Applied & Positive Psychology",
      "Mental Health Awareness",
    ],
    tags: ["Psychology", "Behaviour", "Wellbeing"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Behaviour Journal", desc: "Observe and analyse a behaviour." },
      { title: "Cognition Exercise", desc: "Study a cognitive bias in action." },
      { title: "Personality Reflection", desc: "Apply a personality framework." },
      { title: "Case Discussion", desc: "Analyse a real-world scenario." },
      { title: "Wellbeing Plan", desc: "Design a personal wellbeing plan." },
      { title: "Capstone Reflection", desc: "Applied psychology project." },
    ],
    mentors: [
      { name: "Dr. Ananya Sen", role: "Psychologist", bio: "Counsellor and behavioural science educator." },
      { name: "Rahul Varma", role: "Wellbeing Coach", bio: "Specialist in applied positive psychology." },
    ],
    tools: ["Case Studies", "Assessment Frameworks", "Journaling"],
    outcomes: ["Foundational understanding", "6 reflective projects", "Certificate of completion"],
  },
  {
    slug: "microbiology",
    title: "Microbiology",
    category: "Science & Research",
    level: "Beginner to Intermediate",
    duration: "14 Weeks",
    price_inr: 23999,
    rating: 4.6,
    short_desc: "Study microorganisms and lab techniques for research and healthcare.",
    description:
      "An applied microbiology program covering microbial biology, culturing, and analysis techniques used in clinical, food, and research laboratories.",
    syllabus: [
      "Fundamentals of Microbiology",
      "Microbial Physiology",
      "Culturing & Staining",
      "Microbial Genetics",
      "Clinical & Food Microbiology",
      "Lab Safety & Techniques",
    ],
    tags: ["Microbiology", "LabTechniques", "Research"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Culture Preparation", desc: "Prepare and analyse microbial cultures." },
      { title: "Staining Study", desc: "Gram staining and identification." },
      { title: "Antibiotic Test", desc: "Sensitivity testing write-up." },
      { title: "Water Analysis", desc: "Microbial testing of a sample." },
      { title: "Fermentation Study", desc: "Study microbial fermentation." },
      { title: "Capstone Microbiology Project", desc: "End-to-end lab research report." },
    ],
    mentors: [
      { name: "Dr. Meenakshi Iyer", role: "Microbiologist", bio: "Clinical and research microbiology expert." },
      { name: "Dr. Arun Nair", role: "Lab Scientist", bio: "Specialist in microbial techniques." },
    ],
    tools: ["Microscopy", "Culture Media", "Autoclave", "Lab Instruments"],
    outcomes: ["Lab portfolio", "6 lab projects", "Placement assistance"],
  },
  {
    slug: "nanotechnology",
    title: "Nanotechnology",
    category: "Science & Research",
    level: "Intermediate",
    duration: "14 Weeks",
    price_inr: 27999,
    rating: 4.7,
    short_desc: "Explore nanomaterials, synthesis, and applications across industries.",
    description:
      "A multidisciplinary nanotechnology program covering nanomaterials, characterisation techniques, and applications in medicine, electronics, and energy.",
    syllabus: [
      "Introduction to Nanotechnology",
      "Nanomaterials & Properties",
      "Synthesis Methods",
      "Characterisation Techniques",
      "Nanomedicine & Applications",
      "Safety & Ethics",
    ],
    tags: ["Nanomaterials", "Research", "MaterialsScience"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Nanoparticle Synthesis Plan", desc: "Design a synthesis workflow." },
      { title: "Characterisation Study", desc: "Interpret SEM/TEM data." },
      { title: "Application Review", desc: "Survey a nanotech application." },
      { title: "Material Property Analysis", desc: "Analyse a nanomaterial." },
      { title: "Nanomedicine Case", desc: "Study a drug-delivery system." },
      { title: "Capstone Nanotech Project", desc: "Full applied research report." },
    ],
    mentors: [
      { name: "Dr. Rohit Deshpande", role: "Materials Scientist", bio: "Nanomaterials researcher and educator." },
      { name: "Dr. Priyanka Jain", role: "Nanotech Specialist", bio: "Expert in characterisation techniques." },
    ],
    tools: ["SEM/TEM", "XRD", "Spectroscopy", "Lab Instruments"],
    outcomes: ["Research portfolio", "6 applied projects", "Placement assistance"],
  },
  {
    slug: "product-management",
    title: "Product Management",
    category: "Business & Management",
    level: "Intermediate",
    duration: "14 Weeks",
    price_inr: 29999,
    rating: 4.8,
    short_desc: "Own products end to end — discovery, strategy, roadmaps, and delivery.",
    description:
      "A practical product management program. Learn discovery, prioritisation, roadmapping, metrics, and cross-functional leadership to ship products users love.",
    syllabus: [
      "Product Management Foundations",
      "User Research & Discovery",
      "Prioritisation & Roadmaps",
      "Agile Delivery",
      "Product Metrics & Analytics",
      "Go-to-Market Strategy",
    ],
    tags: ["Product", "Roadmap", "Agile", "Strategy"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Product Discovery", desc: "Research and problem framing." },
      { title: "PRD & Roadmap", desc: "Write a PRD and quarterly roadmap." },
      { title: "Prioritisation Model", desc: "Score and rank a backlog." },
      { title: "Metrics Dashboard", desc: "Define and track product KPIs." },
      { title: "GTM Plan", desc: "Launch plan for a new feature." },
      { title: "Capstone Product Case", desc: "End-to-end product strategy." },
    ],
    mentors: [
      { name: "Ankit Jain", role: "Product Lead", bio: "Shipped products at high-growth startups." },
      { name: "Shreya Nair", role: "Senior PM", bio: "Specialist in discovery and product metrics." },
    ],
    tools: ["Jira", "Figma", "Amplitude", "Notion", "Miro"],
    outcomes: ["PM portfolio", "6 real-world deliverables", "Placement assistance"],
  },
  {
    slug: "bioinformatics",
    title: "Bioinformatics",
    category: "Science & Research",
    level: "Intermediate",
    duration: "16 Weeks",
    price_inr: 28999,
    rating: 4.7,
    short_desc: "Analyse biological data with Python, R, and genomics tools.",
    description:
      "A computational biology program blending biology and data science. Learn sequence analysis, genomics pipelines, and statistical analysis of biological data with Python and R.",
    syllabus: [
      "Biology for Bioinformatics",
      "Python & R for Bio Data",
      "Sequence Analysis",
      "Genomics & NGS Pipelines",
      "Statistical Analysis",
      "Data Visualization",
    ],
    tags: ["Python", "R", "Genomics", "NGS"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Sequence Alignment", desc: "Align and compare sequences." },
      { title: "Variant Analysis", desc: "Call variants from NGS data." },
      { title: "Gene Expression Study", desc: "Analyse RNA-seq data." },
      { title: "Phylogenetic Tree", desc: "Build and interpret a tree." },
      { title: "Bio Data Dashboard", desc: "Visualise a biological dataset." },
      { title: "Capstone Bioinformatics Project", desc: "End-to-end analysis pipeline." },
    ],
    mentors: [
      { name: "Dr. Kiran Rao", role: "Bioinformatician", bio: "Genomics and NGS analysis expert." },
      { name: "Dr. Lena Thomas", role: "Computational Biologist", bio: "Specialist in sequence analysis." },
    ],
    tools: ["Python", "R", "BLAST", "Bioconductor", "Galaxy"],
    outcomes: ["Bioinformatics portfolio", "6 analysis projects", "Placement assistance"],
  },
];

export const seedTestimonials: Testimonial[] = [
  {
    name: "Sneha Pillai",
    role: "Systems Engineer",
    company: "TCS",
    quote:
      "After completing my tech course at Edufyi, I was placed in an internship with one of their partner companies. The experience gave me the exposure and skills I needed to secure a full-time position at TCS.",
    avatar_url: null,
    rating: 5,
  },
  {
    name: "Ankit Rathi",
    role: "Cybersecurity Analyst",
    company: "Deloitte",
    quote:
      "Edufyi Tech Solutions helped me land an internship that allowed me to apply my skills in a real-world setting. That internship was the perfect gateway to my current role at Deloitte.",
    avatar_url: null,
    rating: 5,
  },
  {
    name: "Vishal Khanna",
    role: "Software Developer",
    company: "HCL Technologies",
    quote:
      "The internship opportunities provided by Edufyi are second to none. I got the chance to work on live projects with a reputed firm, which boosted my skills and confidence.",
    avatar_url: null,
    rating: 5,
  },
  {
    name: "Rashmitha",
    role: "Business Analyst",
    company: "Capgemini",
    quote:
      "Edufyi's internships stand out from the rest. Working on live projects with a prestigious company honed my skills and boosted my self-assurance, which soon led to a full-time offer.",
    avatar_url: null,
    rating: 5,
  },
];

export const seedCareerPaths: CareerPath[] = [
  {
    domain: "AI/ML",
    tagline: "Engineer the intelligence behind modern products.",
    roles: [
      { title: "ML Engineer", desc: "Build and deploy models into production." },
      { title: "AI Research Associate", desc: "Prototype novel model architectures." },
      { title: "Computer Vision Engineer", desc: "Work on image and video systems." },
      { title: "NLP Engineer", desc: "Build language and LLM applications." },
    ],
    industries: ["Technology", "Healthcare", "Finance", "Automotive", "E-commerce"],
    progression: [
      { stage: "Junior ML Engineer", years: "0-2 yrs" },
      { stage: "ML Engineer", years: "2-5 yrs" },
      { stage: "Senior / Lead ML", years: "5-8 yrs" },
      { stage: "AI Architect", years: "8+ yrs" },
    ],
  },
  {
    domain: "Data Science",
    tagline: "Turn raw data into decisions that move business.",
    roles: [
      { title: "Data Analyst", desc: "Surface insights from company data." },
      { title: "Data Scientist", desc: "Model and predict business outcomes." },
      { title: "BI Developer", desc: "Build dashboards and reporting." },
      { title: "Analytics Engineer", desc: "Own the data transformation layer." },
    ],
    industries: ["Technology", "Retail", "Banking", "Consulting", "Telecom"],
    progression: [
      { stage: "Data Analyst", years: "0-2 yrs" },
      { stage: "Data Scientist", years: "2-5 yrs" },
      { stage: "Senior Data Scientist", years: "5-8 yrs" },
      { stage: "Head of Data", years: "8+ yrs" },
    ],
  },
  {
    domain: "Cybersecurity",
    tagline: "Defend systems, data, and people from evolving threats.",
    roles: [
      { title: "Security Analyst", desc: "Monitor and respond to threats." },
      { title: "Penetration Tester", desc: "Ethically hack to find weaknesses." },
      { title: "SOC Engineer", desc: "Run security operations." },
      { title: "Security Architect", desc: "Design secure infrastructure." },
    ],
    industries: ["Technology", "Banking", "Government", "Defense", "Healthcare"],
    progression: [
      { stage: "Security Analyst", years: "0-2 yrs" },
      { stage: "Security Engineer", years: "2-5 yrs" },
      { stage: "Senior / SOC Lead", years: "5-8 yrs" },
      { stage: "CISO / Architect", years: "8+ yrs" },
    ],
  },
  {
    domain: "HR",
    tagline: "Build and grow the teams behind great companies.",
    roles: [
      { title: "HR Executive", desc: "Run day-to-day people operations." },
      { title: "Talent Acquisition", desc: "Own hiring end to end." },
      { title: "HR Analyst", desc: "Drive people decisions with data." },
      { title: "HRBP", desc: "Partner with business leaders." },
    ],
    industries: ["Technology", "Manufacturing", "Retail", "Consulting", "Healthcare"],
    progression: [
      { stage: "HR Executive", years: "0-2 yrs" },
      { stage: "HR Specialist", years: "2-5 yrs" },
      { stage: "HR Manager", years: "5-8 yrs" },
      { stage: "Head of People", years: "8+ yrs" },
    ],
  },
];

export const seedSuccessStories: SuccessStory[] = [
  {
    name: "Vishal Khanna",
    program: "AI & Machine Learning",
    domain: "AI/ML",
    outcome: "Placed as Software Developer at HCL Technologies",
    quote:
      "The internship opportunities provided by Edufyi are second to none. I got the chance to work on live projects with a reputed firm, which boosted my skills and confidence.",
    linkedin_url: null,
    company: "HCL Technologies",
    avatar_url: null,
  },
  {
    name: "Jeeva",
    program: "Data Science & Machine Learning",
    domain: "Data Science",
    outcome: "Placed as Data Analyst at Wipro",
    quote:
      "The internships offered by Edufyi are truly exceptional. Gaining hands-on experience through real-world projects at a well-known firm helped me sharpen my skills and build confidence.",
    linkedin_url: null,
    company: "Wipro",
    avatar_url: null,
  },
  {
    name: "Ankit Rathi",
    program: "Cybersecurity Essentials",
    domain: "Cybersecurity",
    outcome: "Placed as Cybersecurity Analyst at Deloitte",
    quote:
      "Edufyi Tech Solutions helped me land an internship that allowed me to apply my skills in a real-world setting. That internship was the perfect gateway to my current role at Deloitte.",
    linkedin_url: null,
    company: "Deloitte",
    avatar_url: null,
  },
  {
    name: "Rashmitha",
    program: "HR Management & Analytics",
    domain: "HR",
    outcome: "Placed as Business Analyst at Capgemini",
    quote:
      "Edufyi's internships stand out from the rest. Working on live projects with a prestigious company honed my skills and boosted my self-assurance.",
    linkedin_url: null,
    company: "Capgemini",
    avatar_url: null,
  },
];
