import type {
  Program,
  Testimonial,
  CareerPath,
  SuccessStory,
} from "./types";

export const seedPrograms: Program[] = [
  {
    slug: "ai-ml",
    title: "AI & Machine Learning",
    category: "AI/ML",
    level: "Beginner to Advanced",
    duration: "24 Weeks",
    price_inr: 34999,
    rating: 4.9,
    short_desc: "Build, train, and deploy intelligent systems from neural nets to LLMs.",
    description:
      "An immersive program that takes you from Python foundations to production-grade AI. Work on real datasets, build deep learning models, and ship an end-to-end AI product with mentor guidance.",
    syllabus: [
      "Python & Math for AI",
      "Machine Learning Foundations",
      "Deep Learning & Neural Networks",
      "Computer Vision",
      "Natural Language Processing & LLMs",
      "MLOps & Model Deployment",
    ],
    tags: ["Python", "TensorFlow", "PyTorch", "LLMs"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Image Classifier", desc: "CNN that recognizes objects in real photos." },
      { title: "Sentiment Engine", desc: "NLP model scoring reviews at scale." },
      { title: "Recommendation System", desc: "Personalized suggestions from user data." },
      { title: "Chatbot with LLMs", desc: "Retrieval-augmented assistant." },
      { title: "Face Detection App", desc: "Real-time computer vision pipeline." },
      { title: "Capstone AI Product", desc: "End-to-end deployed AI service." },
    ],
    mentors: [
      { name: "Dr. Kavya Rao", role: "AI Lead, ex-Google", bio: "10+ years building ML systems at scale." },
      { name: "Arjun Mehta", role: "Senior ML Engineer", bio: "Specialist in NLP and LLM deployment." },
    ],
    tools: ["Python", "TensorFlow", "PyTorch", "Hugging Face", "Docker"],
    outcomes: ["Job-ready AI portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "data-science-ml",
    title: "Data Science & Machine Learning",
    category: "Data Science",
    level: "Intermediate",
    duration: "20 Weeks",
    price_inr: 29999,
    rating: 4.9,
    short_desc: "From Python and statistics to deep learning and model deployment.",
    description:
      "Become a job-ready data scientist. Learn data wrangling, visualization, machine learning algorithms, and how to deploy models to production with real-world datasets.",
    syllabus: [
      "Python for Data Science",
      "Statistics & Probability",
      "Pandas, NumPy & Visualization",
      "Machine Learning with scikit-learn",
      "Deep Learning with TensorFlow",
      "Model Deployment & MLOps",
    ],
    tags: ["Python", "MachineLearning", "TensorFlow", "Pandas"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Sales Forecasting", desc: "Time-series model predicting revenue." },
      { title: "Customer Segmentation", desc: "Clustering users for targeting." },
      { title: "Churn Prediction", desc: "Classify at-risk customers." },
      { title: "A/B Test Analysis", desc: "Statistical experiment evaluation." },
      { title: "Interactive Dashboard", desc: "Business KPIs visualized." },
      { title: "Capstone Analysis", desc: "End-to-end data product." },
    ],
    mentors: [
      { name: "Neha Gupta", role: "Lead Data Scientist", bio: "Drives analytics for a top fintech." },
      { name: "Vikram Singh", role: "Data Science Mentor", bio: "Ex-Amazon, ML & analytics expert." },
    ],
    tools: ["Python", "Pandas", "SQL", "Tableau", "scikit-learn"],
    outcomes: ["Analytics portfolio", "6 real projects", "Placement assistance"],
  },
  {
    slug: "cybersecurity-essentials",
    title: "Cybersecurity Essentials",
    category: "Cybersecurity",
    level: "Beginner to Intermediate",
    duration: "14 Weeks",
    price_inr: 26999,
    rating: 4.7,
    short_desc: "Protect systems and networks with hands-on ethical hacking labs.",
    description:
      "Understand security fundamentals, threat models, and defensive techniques. Practice penetration testing, network security, and incident response in guided labs.",
    syllabus: [
      "Security Fundamentals",
      "Network Security",
      "Ethical Hacking & Pen Testing",
      "Web Application Security",
      "Cryptography Basics",
      "Incident Response",
    ],
    tags: ["Security", "EthicalHacking", "Networking"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Vulnerability Scan", desc: "Assess and report system weaknesses." },
      { title: "Web Pen Test", desc: "Exploit and secure a sample app." },
      { title: "Network Defense Lab", desc: "Configure firewalls and IDS." },
      { title: "Phishing Simulation", desc: "Run and analyze an awareness campaign." },
      { title: "Incident Response Drill", desc: "Detect, contain, and recover." },
      { title: "Capstone Security Audit", desc: "Full assessment of a target system." },
    ],
    mentors: [
      { name: "Rahul Khanna", role: "Security Architect", bio: "CISSP, 12 years in offensive security." },
      { name: "Ananya Iyer", role: "SOC Lead", bio: "Incident response and threat hunting." },
    ],
    tools: ["Kali", "Wireshark", "Metasploit", "Burp", "Nmap"],
    outcomes: ["Hands-on hacking labs", "6 security projects", "Placement assistance"],
  },
  {
    slug: "hr-management",
    title: "HR Management & Analytics",
    category: "HR",
    level: "Beginner to Intermediate",
    duration: "12 Weeks",
    price_inr: 17999,
    rating: 4.7,
    short_desc: "Modern people operations: hiring, engagement, and HR analytics.",
    description:
      "A practical program blending core HR practice with data-driven decision making. Learn recruitment, employee engagement, labor compliance, and how to use analytics to build better teams.",
    syllabus: [
      "Foundations of HR",
      "Talent Acquisition & Recruitment",
      "Employee Engagement & Culture",
      "Compensation & Benefits",
      "HR Analytics & Dashboards",
      "Labor Law & Compliance",
    ],
    tags: ["HR", "Recruitment", "People Analytics"],
    image_url: null,
    is_featured: true,
    projects: [
      { title: "Recruitment Funnel", desc: "Design and measure a hiring pipeline." },
      { title: "Engagement Survey", desc: "Build and analyze employee feedback." },
      { title: "Compensation Plan", desc: "Structure fair, competitive pay bands." },
      { title: "Attrition Dashboard", desc: "Visualize and predict turnover." },
      { title: "Onboarding Program", desc: "Design a 90-day onboarding journey." },
      { title: "Capstone HR Strategy", desc: "Full people strategy for a company." },
    ],
    mentors: [
      { name: "Meera Joshi", role: "Head of People", bio: "Scaled HR for high-growth startups." },
      { name: "Sanjay Patel", role: "HR Analytics Lead", bio: "Turns people data into strategy." },
    ],
    tools: ["Excel", "Power BI", "HRIS", "LinkedIn Recruiter"],
    outcomes: ["HR portfolio", "6 practical projects", "Placement assistance"],
  },
  {
    slug: "full-stack-web-development",
    title: "Full-Stack Web Development",
    category: "Web Development",
    level: "Beginner to Advanced",
    duration: "16 Weeks",
    price_inr: 24999,
    rating: 4.8,
    short_desc: "Master React, Node.js, and databases to build production-grade web apps.",
    description:
      "A comprehensive, project-driven bootcamp covering front-end and back-end engineering. Build and deploy real applications while learning industry best practices, version control, and cloud deployment.",
    syllabus: [
      "HTML, CSS & Modern JavaScript",
      "React & Next.js",
      "Node.js, Express & REST APIs",
      "PostgreSQL & Prisma",
      "Authentication & Security",
      "Deployment & CI/CD",
    ],
    tags: ["React", "Node.js", "PostgreSQL", "Next.js"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "Portfolio Site", desc: "A responsive personal site built with semantic HTML/CSS." },
      { title: "Task Manager App", desc: "Full CRUD app with React state and hooks." },
      { title: "REST API Service", desc: "Node.js/Express API with authentication." },
      { title: "E-commerce Storefront", desc: "Next.js storefront with cart and checkout flow." },
      { title: "Realtime Chat App", desc: "WebSocket-powered live messaging app." },
      { title: "Capstone Full-Stack Product", desc: "End-to-end deployed application with CI/CD." },
    ],
    mentors: [
      { name: "Aditya Rao", role: "Full-Stack Engineer", bio: "Ships production React/Node apps at scale." },
      { name: "Kritika Shah", role: "Senior Frontend Engineer", bio: "Specialist in performant, accessible UIs." },
    ],
    tools: ["React", "Next.js", "Node.js", "PostgreSQL", "Git"],
    outcomes: ["Full-stack portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "cloud-devops",
    title: "Cloud Computing & DevOps",
    category: "Cloud & Infrastructure",
    level: "Intermediate",
    duration: "12 Weeks",
    price_inr: 22999,
    rating: 4.7,
    short_desc: "Deploy, automate, and scale applications on AWS with modern DevOps tools.",
    description:
      "Learn to design resilient cloud infrastructure and automate delivery pipelines. Hands-on with AWS, Docker, Kubernetes, Terraform, and CI/CD workflows.",
    syllabus: [
      "Linux & Networking Fundamentals",
      "AWS Core Services",
      "Docker & Containers",
      "Kubernetes Orchestration",
      "Infrastructure as Code with Terraform",
      "CI/CD Pipelines",
    ],
    tags: ["AWS", "Docker", "Kubernetes", "Terraform"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "CI/CD Pipeline", desc: "Automated build-test-deploy pipeline." },
      { title: "Containerized Microservice", desc: "Dockerized service deployed to the cloud." },
      { title: "Kubernetes Cluster Deployment", desc: "Orchestrate a multi-service app on K8s." },
      { title: "Infrastructure as Code", desc: "Provision cloud resources with Terraform." },
      { title: "Monitoring & Alerting Setup", desc: "Observability stack for a live service." },
      { title: "Capstone Cloud Architecture", desc: "End-to-end resilient infrastructure design." },
    ],
    mentors: [
      { name: "Farhan Ali", role: "Cloud Architect", bio: "Designs resilient AWS infrastructure for scale-ups." },
      { name: "Divya Menon", role: "DevOps Lead", bio: "Automates delivery pipelines for fast-moving teams." },
    ],
    tools: ["AWS", "Docker", "Kubernetes", "Terraform", "GitHub Actions"],
    outcomes: ["Cloud & DevOps portfolio", "6 real-world projects", "Placement assistance"],
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design Masterclass",
    category: "Design",
    level: "Beginner",
    duration: "10 Weeks",
    price_inr: 18999,
    rating: 4.8,
    short_desc: "Design beautiful, user-centered products with Figma and design systems.",
    description:
      "Learn the full product design process: research, wireframing, prototyping, and building scalable design systems. Create a portfolio of real case studies.",
    syllabus: [
      "Design Thinking & Research",
      "Wireframing & Prototyping",
      "Figma Deep Dive",
      "Design Systems",
      "Usability Testing",
      "Portfolio Building",
    ],
    tags: ["Figma", "UX", "UI", "DesignSystems"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "UX Research Case Study", desc: "User interviews and journey mapping for a real product." },
      { title: "Wireframe to Prototype", desc: "Low to high-fidelity interactive prototype." },
      { title: "Design System Build", desc: "Reusable component library in Figma." },
      { title: "Mobile App Redesign", desc: "End-to-end redesign of an existing app flow." },
      { title: "Usability Testing Report", desc: "Run tests and synthesize actionable findings." },
      { title: "Capstone Product Case Study", desc: "Full case study ready for a design portfolio." },
    ],
    mentors: [
      { name: "Ishita Kapoor", role: "Lead Product Designer", bio: "Has shipped design systems for consumer apps." },
      { name: "Rohit Nair", role: "UX Researcher", bio: "Turns user research into product decisions." },
    ],
    tools: ["Figma", "Figjam", "Adobe XD", "Maze"],
    outcomes: ["Design portfolio", "6 real case studies", "Placement assistance"],
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development with React Native",
    category: "Mobile",
    level: "Intermediate",
    duration: "12 Weeks",
    price_inr: 21999,
    rating: 4.6,
    short_desc: "Build cross-platform iOS and Android apps from a single codebase.",
    description:
      "Create native-quality mobile apps using React Native and Expo. Cover navigation, state management, native APIs, and publishing to app stores.",
    syllabus: [
      "React Native Fundamentals",
      "Expo & Tooling",
      "Navigation & State",
      "Native Device APIs",
      "Push Notifications",
      "App Store Deployment",
    ],
    tags: ["ReactNative", "Expo", "Mobile"],
    image_url: null,
    is_featured: false,
    projects: [
      { title: "To-Do List App", desc: "Cross-platform app with local storage." },
      { title: "Weather App", desc: "Consumes a live API with location services." },
      { title: "Social Feed App", desc: "Infinite scroll feed with native gestures." },
      { title: "E-commerce App", desc: "Cart, checkout, and push notifications." },
      { title: "Chat Application", desc: "Realtime messaging with native performance." },
      { title: "Capstone Published App", desc: "App submitted to the App Store / Play Store." },
    ],
    mentors: [
      { name: "Naveen Kumar", role: "Mobile Engineering Lead", bio: "Has shipped React Native apps used by millions." },
      { name: "Pooja Iyer", role: "Mobile Developer", bio: "Specialist in native performance and animations." },
    ],
    tools: ["React Native", "Expo", "Firebase", "TypeScript"],
    outcomes: ["Published app", "6 real-world projects", "Placement assistance"],
  },
];

export const seedTestimonials: Testimonial[] = [
  {
    name: "Sneha Pillai",
    role: "Systems Engineer",
    company: "TCS",
    quote:
      "After completing my tech course at Edufyi, I was placed in an internship with one of their partner companies. The experience gave me the exposure and skills I needed to secure a full-time position at TCS.",
    avatar_url: null,
    rating: 5,
  },
  {
    name: "Ankit Rathi",
    role: "Cybersecurity Analyst",
    company: "Deloitte",
    quote:
      "Edufyi Tech Solutions helped me land an internship that allowed me to apply my skills in a real-world setting. That internship was the perfect gateway to my current role at Deloitte.",
    avatar_url: null,
    rating: 5,
  },
  {
    name: "Vishal Khanna",
    role: "Software Developer",
    company: "HCL Technologies",
    quote:
      "The internship opportunities provided by Edufyi are second to none. I got the chance to work on live projects with a reputed firm, which boosted my skills and confidence.",
    avatar_url: null,
    rating: 5,
  },
  {
    name: "Rashmitha",
    role: "Business Analyst",
    company: "Capgemini",
    quote:
      "Edufyi's internships stand out from the rest. Working on live projects with a prestigious company honed my skills and boosted my self-assurance, which soon led to a full-time offer.",
    avatar_url: null,
    rating: 5,
  },
];

export const seedCareerPaths: CareerPath[] = [
  {
    domain: "AI/ML",
    tagline: "Engineer the intelligence behind modern products.",
    roles: [
      { title: "ML Engineer", desc: "Build and deploy models into production." },
      { title: "AI Research Associate", desc: "Prototype novel model architectures." },
      { title: "Computer Vision Engineer", desc: "Work on image and video systems." },
      { title: "NLP Engineer", desc: "Build language and LLM applications." },
    ],
    industries: ["Technology", "Healthcare", "Finance", "Automotive", "E-commerce"],
    progression: [
      { stage: "Junior ML Engineer", years: "0-2 yrs" },
      { stage: "ML Engineer", years: "2-5 yrs" },
      { stage: "Senior / Lead ML", years: "5-8 yrs" },
      { stage: "AI Architect", years: "8+ yrs" },
    ],
  },
  {
    domain: "Data Science",
    tagline: "Turn raw data into decisions that move business.",
    roles: [
      { title: "Data Analyst", desc: "Surface insights from company data." },
      { title: "Data Scientist", desc: "Model and predict business outcomes." },
      { title: "BI Developer", desc: "Build dashboards and reporting." },
      { title: "Analytics Engineer", desc: "Own the data transformation layer." },
    ],
    industries: ["Technology", "Retail", "Banking", "Consulting", "Telecom"],
    progression: [
      { stage: "Data Analyst", years: "0-2 yrs" },
      { stage: "Data Scientist", years: "2-5 yrs" },
      { stage: "Senior Data Scientist", years: "5-8 yrs" },
      { stage: "Head of Data", years: "8+ yrs" },
    ],
  },
  {
    domain: "Cybersecurity",
    tagline: "Defend systems, data, and people from evolving threats.",
    roles: [
      { title: "Security Analyst", desc: "Monitor and respond to threats." },
      { title: "Penetration Tester", desc: "Ethically hack to find weaknesses." },
      { title: "SOC Engineer", desc: "Run security operations." },
      { title: "Security Architect", desc: "Design secure infrastructure." },
    ],
    industries: ["Technology", "Banking", "Government", "Defense", "Healthcare"],
    progression: [
      { stage: "Security Analyst", years: "0-2 yrs" },
      { stage: "Security Engineer", years: "2-5 yrs" },
      { stage: "Senior / SOC Lead", years: "5-8 yrs" },
      { stage: "CISO / Architect", years: "8+ yrs" },
    ],
  },
  {
    domain: "HR",
    tagline: "Build and grow the teams behind great companies.",
    roles: [
      { title: "HR Executive", desc: "Run day-to-day people operations." },
      { title: "Talent Acquisition", desc: "Own hiring end to end." },
      { title: "HR Analyst", desc: "Drive people decisions with data." },
      { title: "HRBP", desc: "Partner with business leaders." },
    ],
    industries: ["Technology", "Manufacturing", "Retail", "Consulting", "Healthcare"],
    progression: [
      { stage: "HR Executive", years: "0-2 yrs" },
      { stage: "HR Specialist", years: "2-5 yrs" },
      { stage: "HR Manager", years: "5-8 yrs" },
      { stage: "Head of People", years: "8+ yrs" },
    ],
  },
];

export const seedSuccessStories: SuccessStory[] = [
  {
    name: "Vishal Khanna",
    program: "AI & Machine Learning",
    domain: "AI/ML",
    outcome: "Placed as Software Developer at HCL Technologies",
    quote:
      "The internship opportunities provided by Edufyi are second to none. I got the chance to work on live projects with a reputed firm, which boosted my skills and confidence.",
    linkedin_url: null,
    company: "HCL Technologies",
    avatar_url: null,
  },
  {
    name: "Jeeva",
    program: "Data Science & Machine Learning",
    domain: "Data Science",
    outcome: "Placed as Data Analyst at Wipro",
    quote:
      "The internships offered by Edufyi are truly exceptional. Gaining hands-on experience through real-world projects at a well-known firm helped me sharpen my skills and build confidence.",
    linkedin_url: null,
    company: "Wipro",
    avatar_url: null,
  },
  {
    name: "Ankit Rathi",
    program: "Cybersecurity Essentials",
    domain: "Cybersecurity",
    outcome: "Placed as Cybersecurity Analyst at Deloitte",
    quote:
      "Edufyi Tech Solutions helped me land an internship that allowed me to apply my skills in a real-world setting. That internship was the perfect gateway to my current role at Deloitte.",
    linkedin_url: null,
    company: "Deloitte",
    avatar_url: null,
  },
  {
    name: "Rashmitha",
    program: "HR Management & Analytics",
    domain: "HR",
    outcome: "Placed as Business Analyst at Capgemini",
    quote:
      "Edufyi's internships stand out from the rest. Working on live projects with a prestigious company honed my skills and boosted my self-assurance.",
    linkedin_url: null,
    company: "Capgemini",
    avatar_url: null,
  },
];
